## Metadata 
title: Karl Redgate
tagline: Principal Engineer and Architect
author:
  name: Karl N. Redgate
  email: karl.redgate@gmail.com
  givenName: Karl
  familyName: Redgate
  twitter: kredgate
  github: karlredgate
keywords: Xen, Linux, HA, fault tolerance
description: My github pages
repo: https://github.com/karlredgate

# these are available to liquid filters with: site.author.givenName, etc

## Functional configuration 
url: http://linkedin.com/kredgate
permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

markdown: pandoc
pandoc:
   extensions: [smart, mathjax]


# analytics: UA-18401403-1

#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
